print("💡 DỰ ÁN ỨNG DỤNG: HỆ THỐNG ĐIỀU PHỐI XE ĐẠP CÔNG CỘNG (SMART-BIKE)")
print("=" * 70)
print("1. CƠ SỞ DỮ LIỆU: Thu thập lịch sử di chuyển và nhu cầu sử dụng theo khung giờ.")
print("2. PHÂN BỔ TRẠM XE: Chạy thuật toán K-Means (Bài 23.9) để tìm ra các điểm nóng")
print("   (như trạm xe buýt, ký túc xá, cổng trường) để thiết lập bãi đậu xe.")
print("3. CÂN BẰNG SỐ LƯỢNG: Nếu bãi A quá tải xe, bãi B thiếu xe, AI sẽ dùng mạng lưới")
print("   OSMnx và Dijkstra (Bài 23.7) để tìm đường ngắn nhất cho xe tải đến gom và phân bổ lại.")
print("4. GIÁ TRỊ MANG LẠI: Tối ưu hóa chi phí vận hành bãi xe và giúp sinh viên")
print("   luôn có xe để di chuyển nhanh chóng giữa các khu vực.")
print("=" * 70)
